### ISSUE TITLE
CPU usage of BWPing 

### ISSUE THREAD

**Issue by superfeedboy** [oleg-derevenetz/bwping#2]
Hi there,

I'm actually coding a platform to perform multiple bwpings simultaneously to check bandwidth of my customers.
Doing so, i built a docker image with BWPing. The image works pretty well on its own and launchs BWPing as soon as its running.

My problem is that, even with ample resources (CPU, RAM, BW,...), i can't get the container to send more than 100Mbps. And if i try to launch 2 containers with 100Mbps, they fall short at 180Mbps instead of 2x100Mbps.

I saw that containers' CPU usage went to 40-45% each (when bwping PID in the container was going 100%).

I'm aiming to test 1Gbps but, as for now, i have to launch 5 containers, each trying to send 1Gbps, to reach the 1Gbps total TX out of the host (which can manage 5,6Gbps).

Do you have any idea about this issue and how i could get through it?

Best regards,
SuperFeedBoy

**Comment by oleg-derevenetz** [comment]
Hi,

I can suggest you try the following:

1. Try to run bwping on the same hardware, but without docker. Will there be any difference?
2. What packet size do you use? Try increasing it (ideally equal to the network interface MTU). Sending a large number of small packets may require more system resources than sending a smaller number of larger packets.

**Comment by superfeedboy** [comment]
Hi Oleg,

For the points you suggested:

1. i can see no difference running it on the host :(
2. i usually set 1280 but i tried higher pkt size with no significant improvement though

The host is running on Xeon E5410 with 4 CPU x 4 cores. I checked how they manage multiple docker containers running 100Mbps test each and i saw that CPU 1 and CPU 3 were taking the charge and CPU 2 and CPU 4 were pretty puch idle.

I'll try 2 workarounds:

1. set my containers to user specific CPUs by adding **--cpuset-cpus="1,2,..."** on my **docker run** command
2. set which core(s) must handle bwping when running bwping through **taskset -c 0,1,...** inside the container

I'll let you know on monday ;)

In the meanwhile, feel free to provide me with some other ideas! :)

**Comment by oleg-derevenetz** [comment]
bwping is single-threaded, so if it consumes 100% CPU, then it would be right to try to bound each container to separate CPU. What really sounds weird is such a large CPU load when sending only 100Mbps. I just tried to do this on my Windows PC (with Core i7-3770K and 100Mbit Ethernet connection to local router), and bwping CPU usage was just about 2-3%:

![bwping_cpu](https://user-images.githubusercontent.com/32623900/92257973-c6949c80-eede-11ea-91fe-c6129f4a9ed8.jpg)

I'll think about it again, maybe there will be some ideas.

**Comment by oleg-derevenetz** [comment]
I have an idea to try adding support for linux-specific sendmmsg()/recvmmsg() as an alternative to sendto()/recvmsg() pair that is currently used. This should (in theory) reduce the number of context switches and increase performance. But how much this will help is still unknown.

**Comment by oleg-derevenetz** [comment]
You can try experimental "mmsg" branch with support for linux-specific sendmmsg()/recvmmsg() calls:

https://github.com/oleg-derevenetz/bwping/tree/mmsg

Using these system calls should significantly reduce the number of context switches (dozens of times depending on the tested speed and packet size), this should reduce the CPU load.

**Comment by oleg-derevenetz** [comment]
In addition, I can suggest you try to manually tune bufsize using the -u switch. The default values are about 150-200 KB, which may not be enough for speeds of several hundred Mbps (the specific value depends on the resolution of the system timer and the overall system load).

**Comment by superfeedboy** [comment]
Hi Oleg,

Thank you very much. I'll be testing it today and provide you with feedbacks of the tests ;)

My test proto is like:

1. test mmsg branch on linux host
2. if OK (or at least "better", which should be the case regarding how sendmmsg() works) -> create a deb package
3. push deb package in Docker Image
4. try a single container at 100, 300Mbps and 1Gbps with -u over 1024KB
5. try multiple containers running 100Mbps each -u over 1024KB
6. maybe try --cpuset-cpus="1,2,..." if needed
7. maybe try taskset -c 0,1 while running bwping in the container if needed

I'll get back to asap!
SFB

**Comment by superfeedboy** [comment]
Hi again Oleg,

As for now, i tried **mmsg** branch version on the host and saw that the test begins and seems to work but  8 sec later i see weird behaviour:
**Testing 100Mbps**:

| Timeline | CPU usage (%) | BW Bps | BW Mbps |
|:-:|:-:|:-:|:-:|
| < 8sec | 25-27% | 12840704 | 102.72 |
| > 8sec | 2-3% | 254 | 0.002 |

![image](https://user-images.githubusercontent.com/34971399/92386239-b1ed1a00-f113-11ea-9b9f-f7904bc033c1.png)

I also saw that setting buffer >= 1024 tends to brings some errors:
**Testing 100Mbps**:

> bwping: sendmmsg() failed: No buffer space available

_(appears 5 to 10 times)_
**Testing 1Gbps**:

> bwping: sendmmsg() warning: packets to send: 6, sent: 5

_(appears multiple times)_

**Comment by oleg-derevenetz** [comment]
What value do you pass as the buffer size? Remember that it should be in bytes, not in KB, so it should be 1024000, not 1024. Buffer size of 1024 bytes is indeed to small.

**Comment by superfeedboy** [comment]
True enough -_-'

Using a Bytes buffer avoids those errors but i still have the "8sec problem" :P

**Comment by oleg-derevenetz** [comment]
Could you share the exact launch parameters? I tested mmsg branch on Linux (although running in VMware), and it seems to work fine. I'm going to test it later today on "real" hardware with 100Mbit and 1Gbit NICs.

**Comment by oleg-derevenetz** [comment]
250 mbytes could be sent over 1Gbps link in 8 seconds. Could you add a few more zeroes to volume and send me bwping output (no up addresses required)?

**Comment by oleg-derevenetz** [comment]
According to bwping output, it continues to receive about 100 Mbps even on latest seconds. For example, 406407680 - 392485120 = 13922560 bytes, roughly 111 Mbps.

**Comment by superfeedboy** [comment]
Should be at 1Gbps though 

> transfer speed: 1000000 kbps

I'll perform a new battery of tests and provide you with the feedbacks ;)

**Comment by oleg-derevenetz** [comment]
Yes, but it depends on other side as well. According to bwping output, many sent packets were lost, about 2/3. Speed is measured based on replies, not on sent packets. It seems that output speed is about 300Mbps, while input is about 112Mbps.

**Comment by superfeedboy** [comment]
Actually, i'm checking TXBytes and see that i reach 53063225 Bps (424.50 Mbps) instead of 1Gbps.
What seems weird to me is that, ss i'm checking on the WAN NIC, i should be close to the 1Gbps though?

**Comment by oleg-derevenetz** [comment]
Yes, in perfect conditions... But in reality there are many factors. For example, when you sending data over TCP, you generally can achieve 1Gpbs due to DMA between RAM and NIC and packet offloading techniques. However, when you sending data over ICMP (like bwping does) there is no offloading, so every packet should be prepared on CPU. I suggest to read this article:

https://blog.cloudflare.com/accelerating-udp-packet-transmission-for-quic/

It's about UDP, but much of this applies to ICMP as well (except that, for example, there is no flag like UDP_SEGMENT, but for ICMP).

**Comment by oleg-derevenetz** [comment]
I tested the mmsg branch tonight on some linux machines with 1Gbit NICs, was able to achieve ~500Mbps. After that I added some optimizations (mostly related to checksum calculation and working with buffers), which I plan to test tomorrow. These optimizations are available in mmsg branch on github, you can try it yourself if you want.

**Comment by oleg-derevenetz** [comment]
According to the results of today's tests, I managed to achieve speed of ~800 Mbps on Linux and ~700Mbps on Mac OS. I merged recent changes to master branch and going to make a new release with these changes soon.

**Comment by oleg-derevenetz** [comment]
Another improvement approach: https://github.com/oleg-derevenetz/bwping/commit/59f5051993a7a7f4c842b10248d57a4cc1818758 to filter incoming ICMP packets destined to this particular process (based on ICMP id) on early stages in kernel. This should (in theory) show some improvement in the case of multiple bwping processes running on the same machine, but the effect has yet to be evaluated in tests on real high-speed networks.

**Comment by superfeedboy** [comment]
Hi Oleg,

Glad to read this ☺️ I may help you on the tests as i can reach 5-6Gbps with my server (towards the internet)!

**Comment by oleg-derevenetz** [comment]
Hi @superfeedboy of course any test results are welcome :)

**Comment by superfeedboy** [comment]
Hi @oleg-derevenetz 

I've ran some tests and got stuck at around 1.5Gbps which is an absolute great improvement for me! I believe that i can't go further due to the hardware of the server (a bit deprecated i'd say).

![image](https://user-images.githubusercontent.com/34971399/93107468-ed5a8c00-f6b1-11ea-8240-6b9ca4136f02.png)

Running 2 bwping at 1Gbps each with different PIDs on different cores of the host ends up in:
- PID 1: 100% (1Gbps at 78% CPU)
- PID 2: 70% (700Mbps at 82% CPU)

Again, i think this is due to the old hardware.

I'll ask a mate to test on different hardware and provide you with his feedback ;)

**Comment by oleg-derevenetz** [comment]
Hi @superfeedboy

Thanks, it looks great! Have you tried disabling BPF (by running configure --disable-bpf), running the same multi-process configuration with 2 bwpings again and then comparing results? It would be interesting to know how much the presence of the BPF affects the results.

With best regards, Oleg.

**Comment by oleg-derevenetz** [comment]
BTW, please note that BPF filters incoming packets (ICMP replies from the other side), so you should see an improvement only if you get large volumes back.

**Comment by CfYz-R** [comment]
Hi, Oleg @oleg-derevenetz 

> Have you tried disabling BPF (by running configure --disable-bpf), running the same multi-process 
This **--disable-bpf** parameter is for compiling BWPing, right?

**Comment by oleg-derevenetz** [comment]
@CfYz-R Yes, it's for configure script.
